//  ДЕРЖАТЬ СЛОВАРНЫЕ СТАТЬИ ОТСОРТИРОВАННЫМИ ПО УРОКАМ !!!

export var entries = [
    { "lesson": 1, "hieroglyph": "你", "pinyin": "Nǐ", "translation": "ты" },
    { "lesson": 1, "hieroglyph": "好", "pinyin": "Hǎo", "translation": "хорошо, хороший" },
    { "lesson": 1, "hieroglyph": "人", "pinyin": "Rén", "translation": "человек" },
    { "lesson": 1, "hieroglyph": "女", "pinyin": "Nǚ", "translation": "женщина" },
    { "lesson": 1, "hieroglyph": "子", "pinyin": "Zǐ", "translation": "ребенок" },
    { "lesson": 2, "hieroglyph": "吗", "pinyin": "Мa", "translation": "(вопросит. частица)" },
    { "lesson": 2, "hieroglyph": "我", "pinyin": "Wǒ", "translation": "я" },
    { "lesson": 2, "hieroglyph": "很", "pinyin": "Hěn", "translation": "очень" },
    { "lesson": 2, "hieroglyph": "呢", "pinyin": "Ne", "translation": "(модальная частица)" },
    { "lesson": 2, "hieroglyph": "也", "pinyin": "Yě", "translation": "тоже, также, и" },
    { "lesson": 2, "hieroglyph": "口", "pinyin": "Kǒu", "translation": "рот" },
    { "lesson": 2, "hieroglyph": "马", "pinyin": "Mǎ", "translation": "лошадь" },
    { "lesson": 2, "hieroglyph": "艮", "pinyin": "Gěn", "translation": "твердый" },
    { "lesson": 2, "hieroglyph": "彳", "pinyin": "Chì", "translation": "шаг" },
    { "lesson": 2, "hieroglyph": "尸", "pinyin": "Shī", "translation": "труп" },
    { "lesson": 2, "hieroglyph": "匕", "pinyin": "Bǐ", "translation": "ложка, черпак" },
    { "lesson": 3, "hieroglyph": "忙", "pinyin": "Máng", "translation": "занятый" },
    { "lesson": 3, "hieroglyph": "不", "pinyin": "Bù", "translation": "нет, не" },
    { "lesson": 3, "hieroglyph": "弟弟", "pinyin": "Dìdì", "translation": "младший брат" },
    { "lesson": 3, "hieroglyph": "哥哥", "pinyin": "Gēgē", "translation": "старший брат" },
    { "lesson": 3, "hieroglyph": "他们", "pinyin": "Tāmen", "translation": "они (любые, одуш)" },
    { "lesson": 3, "hieroglyph": "她们", "pinyin": "Tāmen", "translation": "они (женщины)" },
    { "lesson": 3, "hieroglyph": "他", "pinyin": "Tā", "translation": "он" },
    { "lesson": 3, "hieroglyph": "她", "pinyin": "Tā", "translation": "она" },
    { "lesson": 3, "hieroglyph": "都", "pinyin": "Dōu", "translation": "все, всё" },
    { "lesson": 3, "hieroglyph": "心", "pinyin": "Xīn", "translation": "сердце" },
    { "lesson": 3, "hieroglyph": "土", "pinyin": "Tǔ", "translation": "земля" },
    { "lesson": 3, "hieroglyph": "日", "pinyin": "Rì", "translation": "солнце" },
    { "lesson": 3, "hieroglyph": "阝", "pinyin": "yì", "translation": "город" },
    { "lesson": 3, "hieroglyph": "门", "pinyin": "Mén", "translation": "ворота, дверь" },
    { "lesson": 4, "hieroglyph": "这", "pinyin": "Zhè", "translation": "это, этот" },
    { "lesson": 4, "hieroglyph": "朋友", "pinyin": "Péngyǒu", "translation": "друг" },
    { "lesson": 4, "hieroglyph": "爸爸", "pinyin": "Bàba", "translation": "папа" },
    { "lesson": 4, "hieroglyph": "你们", "pinyin": "Nǐmen", "translation": "вы" },
    { "lesson": 4, "hieroglyph": "是", "pinyin": "Shì", "translation": "есть, являться" },
    { "lesson": 4, "hieroglyph": "妈妈", "pinyin": "Māmā", "translation": "мать" },
    { "lesson": 4, "hieroglyph": "文", "pinyin": "Wén", "translation": "знак, письмена" },
    { "lesson": 4, "hieroglyph": "月", "pinyin": "Yuè", "translation": "месяц" },
    { "lesson": 5, "hieroglyph": "??", "pinyin": "Zhǐ", "translation": "бумага" },
    { "lesson": 5, "hieroglyph": "??", "pinyin": "Bào", "translation": "газета (+ название)" },
    { "lesson": 5, "hieroglyph": "??", "pinyin": "Bàozhǐ", "translation": "газета (в общем)" },
    { "lesson": 5, "hieroglyph": "??", "pinyin": "Chǐ", "translation": "линейка" },
    { "lesson": 5, "hieroglyph": "??", "pinyin": "Bǐ", "translation": "орудие письма" },
    { "lesson": 5, "hieroglyph": "大夫", "pinyin": "Dàifū", "translation": "доктор" },
    { "lesson": 5, "hieroglyph": "的", "pinyin": "De", "translation": "служ. слово" },
    { "lesson": 5, "hieroglyph": "车", "pinyin": "Chē", "translation": "автомобиль, колесный транспорт" },
    { "lesson": 5, "hieroglyph": "那", "pinyin": "Nà", "translation": "тот, та, то, те" },
    { "lesson": 5, "hieroglyph": "书", "pinyin": "Shū", "translation": "Книга" },
    { "lesson": 5, "hieroglyph": "是", "pinyin": "Shì", "translation": "да, так, правильно" },
    { "lesson": 5, "hieroglyph": "白", "pinyin": "Bái", "translation": "белый" },
    { "lesson": 5, "hieroglyph": "勺", "pinyin": "Sháo", "translation": "столовая ложка, половник" },
    { "lesson": 5, "hieroglyph": "夫", "pinyin": "Fū", "translation": "муж" },
    { "lesson": 5, "hieroglyph": "大", "pinyin": "Dà, Dài", "translation": "Большой" },
    { "lesson": 6, "hieroglyph": "??", "pinyin": "Èluósī", "translation": "Россия" },
    { "lesson": 6, "hieroglyph": "??", "pinyin": "Déguó", "translation": "Германия" },
    { "lesson": 6, "hieroglyph": "??", "pinyin": "Fàguó", "translation": "Франция" },
    { "lesson": 6, "hieroglyph": "??", "pinyin": "Měiguó", "translation": "США" },
    { "lesson": 6, "hieroglyph": "??", "pinyin": "Rìběn", "translation": "Япония" },
    { "lesson": 6, "hieroglyph": "??", "pinyin": "Tàiguó", "translation": "Таиланд" },
    { "lesson": 6, "hieroglyph": "杖", "pinyin": "zhàng", "translation": "стержень, жезл" },
    { "lesson": 6, "hieroglyph": "哪", "pinyin": "Nǎ", "translation": "который, какой" },
    { "lesson": 6, "hieroglyph": "国", "pinyin": "Guó", "translation": "страна, государство" },
    { "lesson": 6, "hieroglyph": "谁", "pinyin": "Shéi", "translation": "Кто" },
    { "lesson": 6, "hieroglyph": "老师", "pinyin": "Lǎoshī", "translation": "учитель" },
    { "lesson": 6, "hieroglyph": "汉", "pinyin": "Hàn", "translation": "династия Хань" },
    { "lesson": 6, "hieroglyph": "语", "pinyin": "Yǔ", "translation": "язык" },
    { "lesson": 6, "hieroglyph": "汉语", "pinyin": "hànyǔ", "translation": "китайский язык" },
    { "lesson": 6, "hieroglyph": "中国", "pinyin": "Zhōngguó", "translation": "Китай" },
    { "lesson": 6, "hieroglyph": "老", "pinyin": "Lǎo", "translation": "Старый" },
    { "lesson": 6, "hieroglyph": "师", "pinyin": "Shī", "translation": "учитель, мастер" },
    { "lesson": 6, "hieroglyph": "王", "pinyin": "Wáng", "translation": "император" },
    { "lesson": 6, "hieroglyph": "玉", "pinyin": "Yù", "translation": "нефрит" },
    { "lesson": 6, "hieroglyph": "言", "pinyin": "Yán", "translation": "речь" },
    { "lesson": 6, "hieroglyph": "隹", "pinyin": "zhuī", "translation": "короткохвостка" },
    { "lesson": 6, "hieroglyph": "水", "pinyin": "Shuǐ", "translation": "вода" },
    { "lesson": 6, "hieroglyph": "中", "pinyin": "Zhōng", "translation": "середина" },
    { "lesson": 6, "hieroglyph": "囗", "pinyin": "<i>no pinyin</i>", "translation": "ограда" },
    { "lesson": 6, "hieroglyph": "又", "pinyin": "Yòu", "translation": "ладонь" },
    { "lesson": 7, "hieroglyph": "??", "pinyin": "Běijīng", "translation": "Пекин" },
    { "lesson": 7, "hieroglyph": "??", "pinyin": "Shànghǎi", "translation": "Шанхай" },
    { "lesson": 7, "hieroglyph": "??", "pinyin": "Chángjiāng", "translation": "река Янцзы (Чанцзян)" },
    { "lesson": 7, "hieroglyph": "??", "pinyin": "Huánghé", "translation": "река Хуанхэ" },
    { "lesson": 7, "hieroglyph": "??", "pinyin": "chángchéng", "translation": "Великая Китайская стена" },
    { "lesson": 7, "hieroglyph": "??", "pinyin": "Shìjiè", "translation": "мир, вселенная" },
    { "lesson": 7, "hieroglyph": "??", "pinyin": "Ōuzhōu", "translation": "Европа" },
    { "lesson": 7, "hieroglyph": "??", "pinyin": "Yàzhōu", "translation": "Азия" },
    { "lesson": 7, "hieroglyph": "??", "pinyin": "Měizhōu", "translation": "Америка" },
    { "lesson": 7, "hieroglyph": "??", "pinyin": "Fēizhōu", "translation": "Африка" },
    { "lesson": 7, "hieroglyph": "??", "pinyin": "Dàyángzhōu", "translation": "Океания" },
    { "lesson": 7, "hieroglyph": "什么", "pinyin": "Shénme", "translation": "что, какой" },
    { "lesson": 7, "hieroglyph": "地图", "pinyin": "Dìtú", "translation": "географическая карта" },
    { "lesson": 7, "hieroglyph": "地", "pinyin": "Dì", "translation": "земля, почва" },
    { "lesson": 7, "hieroglyph": "图", "pinyin": "Tú", "translation": "схема, иллюстрация, рисунок" },
    { "lesson": 7, "hieroglyph": "看", "pinyin": "Kàn", "translation": "читать, смотреть, думать, понимать" },
    { "lesson": 7, "hieroglyph": "手", "pinyin": "Shǒu", "translation": "рука" },
    { "lesson": 7, "hieroglyph": "目", "pinyin": "Mù", "translation": "глаз" },
    { "lesson": 8, "hieroglyph": "??", "pinyin": "kāfēi", "translation": "кофе" },
    { "lesson": 8, "hieroglyph": "??", "pinyin": "píjiŭ", "translation": "пиво" },
    { "lesson": 8, "hieroglyph": "??", "pinyin": "niúnăi", "translation": "молоко" },
    { "lesson": 8, "hieroglyph": "??", "pinyin": "xiānsheng", "translation": "господин" },
    { "lesson": 8, "hieroglyph": "??", "pinyin": "tàitai", "translation": "госпожа" },
    { "lesson": 8, "hieroglyph": "水", "pinyin": "shuĭ", "translation": "вода" },
    { "lesson": 8, "hieroglyph": "请", "pinyin": "qĭng", "translation": "просить, пожалуйста, приглашать" },
    { "lesson": 8, "hieroglyph": "喝", "pinyin": "hē", "translation": "пить" },
    { "lesson": 8, "hieroglyph": "茶", "pinyin": "chá", "translation": "чай" },
    { "lesson": 8, "hieroglyph": "您", "pinyin": "nín", "translation": "Вы (уважит)" },
    { "lesson": 8, "hieroglyph": "进", "pinyin": "jìn", "translation": "входить" },
    { "lesson": 8, "hieroglyph": "欢迎", "pinyin": "huányíng", "translation": "приветствовать" },
    { "lesson": 8, "hieroglyph": "谢谢", "pinyin": "xièxiè", "translation": "спасибо" },
    { "lesson": 8, "hieroglyph": "客气", "pinyin": "kèqi", "translation": "вежливый" },
    { "lesson": 8, "hieroglyph": "吸烟", "pinyin": "xīyān", "translation": "курить" },
    { "lesson": 8, "hieroglyph": "吸", "pinyin": "xī", "translation": "вдыхать" },
    { "lesson": 8, "hieroglyph": "烟", "pinyin": "yān", "translation": "дым" },
    { "lesson": 8, "hieroglyph": "青", "pinyin": "qīng", "translation": "зеленый, синий, черный (поэтич)" },
    { "lesson": 8, "hieroglyph": "日", "pinyin": "yuē", "translation": "говорить" },
    { "lesson": 8, "hieroglyph": "艸", "pinyin": "căo", "translation": "трава" },
    { "lesson": 8, "hieroglyph": "木", "pinyin": "mù", "translation": "дерево" },
    { "lesson": 8, "hieroglyph": "井", "pinyin": "jĭng", "translation": "колодец" },
    { "lesson": 8, "hieroglyph": "欠", "pinyin": "qiàn", "translation": "недоставать, нехватать" },
    { "lesson": 8, "hieroglyph": "寸", "pinyin": "cūn", "translation": "вершок" },
    { "lesson": 8, "hieroglyph": "气", "pinyin": "qì", "translation": "пар, дым, газ" },
    { "lesson": 8, "hieroglyph": "宀", "pinyin": "<i>no pinyin</i>", "translation": "крыша с точкой" },
    { "lesson": 8, "hieroglyph": "火", "pinyin": "huŏ", "translation": "огонь" },
    { "lesson": 8, "hieroglyph": "身", "pinyin": "shēn", "translation": "тело" },
    { "lesson": 9, "hieroglyph": "??", "pinyin": "Dīng Yún", "translation": "Дин Юнь (фамилия)" },
    { "lesson": 9, "hieroglyph": "??", "pinyin": "nǚshì", "translation": "госпожа, дама" },
    { "lesson": 9, "hieroglyph": "??", "pinyin": "Yīngguó", "translation": "Англия" },
    { "lesson": 9, "hieroglyph": "??", "pinyin": "Cháoxiăn", "translation": "Северная Корея" },
    { "lesson": 9, "hieroglyph": "??", "pinyin": "xiǎojie", "translation": "леди, девушка легкого поведения" },
    { "lesson": 9, "hieroglyph": "贵姓", "pinyin": "guì xìng", "translation": "как Ваша фамилия?" },
    { "lesson": 9, "hieroglyph": "贵", "pinyin": "guì", "translation": "дорогой, знатный" },
    { "lesson": 9, "hieroglyph": "姓", "pinyin": "xìng", "translation": "называться по фамилии, фамилия" },
    { "lesson": 9, "hieroglyph": "请问", "pinyin": "qĭng wèn", "translation": "позвольте спросить" },
    { "lesson": 9, "hieroglyph": "问", "pinyin": "wèn", "translation": "спрашивать" },
    { "lesson": 9, "hieroglyph": "留学生", "pinyin": "liúxuéshēng", "translation": "студент-иностранец" },
    { "lesson": 9, "hieroglyph": "叫", "pinyin": "jiào", "translation": "звать, называть, называться, именоваться" },
    { "lesson": 9, "hieroglyph": "外语", "pinyin": "wàiyŭ", "translation": "иностранный язык" },
    { "lesson": 9, "hieroglyph": "外", "pinyin": "wài", "translation": "внешний, иностранный" },
    { "lesson": 9, "hieroglyph": "学生", "pinyin": "xuésheng", "translation": "ученик, школьник, студент" },
    { "lesson": 9, "hieroglyph": "学习", "pinyin": "xuéxí", "translation": "учиться, изучать (что угодно или что-то конкретное)" },
    { "lesson": 9, "hieroglyph": "学院", "pinyin": "xuéyuàn", "translation": "институт" },
    { "lesson": 9, "hieroglyph": "学", "pinyin": "xué", "translation": "учиться, изучать (что-то конкретное)" },
    { "lesson": 9, "hieroglyph": "习", "pinyin": "xí", "translation": "повторять изученное" },
    { "lesson": 9, "hieroglyph": "院", "pinyin": "yuàn", "translation": "двор" },
    { "lesson": 9, "hieroglyph": "留", "pinyin": "liú", "translation": "оставлять" },
    { "lesson": 9, "hieroglyph": "贝", "pinyin": "bèi", "translation": "раковина" },
    { "lesson": 9, "hieroglyph": "生", "pinyin": "shēng", "translation": "рожать, сырой, свежий" },
    { "lesson": 9, "hieroglyph": "刀", "pinyin": "dāo", "translation": "нож" },
    { "lesson": 9, "hieroglyph": "田", "pinyin": "tián", "translation": "поле" },
    { "lesson": 9, "hieroglyph": "夕", "pinyin": "xī", "translation": "вечер" },
    { "lesson": 9, "hieroglyph": "卜", "pinyin": "bŭ", "translation": "гадать" },
    { "lesson": 9, "hieroglyph": "β", "pinyin": "fù", "translation": "гора, холм" },
    { "lesson": 10, "hieroglyph": "??", "pinyin": "yīyuàn", "translation": "больница, лечебница" },
    { "lesson": 10, "hieroglyph": "??", "pinyin": "zhèr", "translation": "здесь, сюда" },
    { "lesson": 10, "hieroglyph": "??", "pinyin": "nàr", "translation": "там, туда" },
    { "lesson": 10, "hieroglyph": "O", "pinyin": "líng", "translation": "0" },
    { "lesson": 10, "hieroglyph": "一", "pinyin": "yī", "translation": "1" },
    { "lesson": 10, "hieroglyph": "二", "pinyin": "èr", "translation": "2" },
    { "lesson": 10, "hieroglyph": "三", "pinyin": "sān", "translation": "3" },
    { "lesson": 10, "hieroglyph": "四", "pinyin": "sì", "translation": "4" },
    { "lesson": 10, "hieroglyph": "五", "pinyin": "wŭ", "translation": "5" },
    { "lesson": 10, "hieroglyph": "在", "pinyin": "zài", "translation": "находиться, в, на" },
    { "lesson": 10, "hieroglyph": "坐", "pinyin": "zuò", "translation": "сидеть, садиться" },
    { "lesson": 10, "hieroglyph": "哪儿", "pinyin": "năr", "translation": "где, куда" },
    { "lesson": 10, "hieroglyph": "宿舍", "pinyin": "sùshè", "translation": "общежитие, комната в общежитии" },
    { "lesson": 10, "hieroglyph": "住", "pinyin": "zhù", "translation": "жить, проживать" },
    { "lesson": 10, "hieroglyph": "多少", "pinyin": "duōshao", "translation": "сколько" },
    { "lesson": 10, "hieroglyph": "多", "pinyin": "duō", "translation": "много" },
    { "lesson": 10, "hieroglyph": "少", "pinyin": "shăo", "translation": "мало" },
    { "lesson": 10, "hieroglyph": "号", "pinyin": "hào", "translation": "номер, число (дата)" },
    { "lesson": 10, "hieroglyph": "层", "pinyin": "céng", "translation": "этаж, слой, ярус" },
    { "lesson": 10, "hieroglyph": "同志", "pinyin": "tóngzhì", "translation": "товарищ, гей" },
    { "lesson": 10, "hieroglyph": "厕所", "pinyin": "cèsuŏ", "translation": "туалет" },
    { "lesson": 10, "hieroglyph": "百", "pinyin": "băi", "translation": "100" },
    { "lesson": 10, "hieroglyph": "舌", "pinyin": "shé", "translation": "язык (ч тела)" },
    { "lesson": 10, "hieroglyph": "云", "pinyin": "yún", "translation": "облако" },
    { "lesson": 11, "hieroglyph": "??", "pinyin": "zázhì", "translation": "текстовой журнал" },
    { "lesson": 11, "hieroglyph": "??", "pinyin": "diànhuà", "translation": "телефон" },
    { "lesson": 11, "hieroglyph": "??", "pinyin": "bĕnzi", "translation": "тетрадь" },
    { "lesson": 11, "hieroglyph": "??", "pinyin": "yŭsăn", "translation": "зонтик" },
    { "lesson": 11, "hieroglyph": "还", "pinyin": "huán", "translation": "вернуть, возвращать, отдавать обратно" },
    { "lesson": 11, "hieroglyph": "画报", "pinyin": "huàbào", "translation": "иллюстрированный журнал" },
    { "lesson": 11, "hieroglyph": "画", "pinyin": "huà", "translation": "картина, рисунок, рисовать, изображать" },
    { "lesson": 11, "hieroglyph": "报", "pinyin": "bào", "translation": "газета" },
    { "lesson": 11, "hieroglyph": "词典", "pinyin": "cídiăn", "translation": "словарь" },
    { "lesson": 11, "hieroglyph": "词", "pinyin": "cí", "translation": "слово" },
    { "lesson": 11, "hieroglyph": "典", "pinyin": "diăn", "translation": "канон, сборник" },
    { "lesson": 11, "hieroglyph": "现在", "pinyin": "xiànzài", "translation": "теперь, сейчас, в настоящее время" },
    { "lesson": 11, "hieroglyph": "用", "pinyin": "yòng", "translation": "употреблять, применять, использовать, пользоваться" },
    { "lesson": 11, "hieroglyph": "一下儿", "pinyin": "yíxiàr", "translation": "разок, немного, недолго" },
    { "lesson": 11, "hieroglyph": "再见", "pinyin": "zàijiàn", "translation": "\"до свидания\", \"до встречи\", \"пока\" (ещё раз увидеться)" },
    { "lesson": 11, "hieroglyph": "六", "pinyin": "liù", "translation": "шесть" },
    { "lesson": 11, "hieroglyph": "七", "pinyin": "qī", "translation": "семь" },
    { "lesson": 11, "hieroglyph": "八", "pinyin": "bā", "translation": "восемь" },
    { "lesson": 11, "hieroglyph": "九", "pinyin": "jiŭ", "translation": "девять" },
    { "lesson": 11, "hieroglyph": "十", "pinyin": "shí", "translation": "десять" },
    { "lesson": 11, "hieroglyph": "巳", "pinyin": "jié", "translation": "печать, власть" },
    { "lesson": 12, "hieroglyph": "先生", "pinyin": "xiānsheng", "translation": "мистер, господин" },
    { "lesson": 12, "hieroglyph": "先", "pinyin": "xiān", "translation": "сначала, сперва, предок, раньше" },
    { "lesson": 12, "hieroglyph": "认识", "pinyin": "rènshi", "translation": "быть знакомым, знакомиться, опознавать, узнавать" },
    { "lesson": 12, "hieroglyph": "认", "pinyin": "rèn", "translation": "знать, узнавать" },
    { "lesson": 12, "hieroglyph": "识", "pinyin": "shi", "translation": "знать" },
    { "lesson": 12, "hieroglyph": "俄语", "pinyin": "éyŭ", "translation": "русский язык" },
    { "lesson": 12, "hieroglyph": "英语", "pinyin": "yīngyŭ", "translation": "английский язык" },
    { "lesson": 12, "hieroglyph": "英", "pinyin": "yīng", "translation": "цветение, цветок" },
    { "lesson": 12, "hieroglyph": "常", "pinyin": "cháng", "translation": "часто, всегда" },
    { "lesson": 12, "hieroglyph": "去", "pinyin": "qù", "translation": "идти, ехать, направляться" },
    { "lesson": 12, "hieroglyph": "俄罗斯", "pinyin": "Éluósī", "translation": "Россия" },
    { "lesson": 12, "hieroglyph": "法国", "pinyin": "Făguó", "translation": "Франция" },
    { "lesson": 12, "hieroglyph": "女朋友", "pinyin": "Nǚ péngyǒu", "translation": "девушка" },
    { "lesson": 12, "hieroglyph": "男朋友", "pinyin": "Nán péngyǒu", "translation": "парень" },
    { "lesson": 12, "hieroglyph": "男", "pinyin": "Nán", "translation": "мужчина" },
    { "lesson": 13, "hieroglyph": "纟系", "pinyin": "nì", "translation": "нить шелк" },
    { "lesson": 13, "hieroglyph": "本子", "pinyin": "bĕnzi", "translation": "тетрадь" },
    { "lesson": 13, "hieroglyph": "邮局", "pinyin": "yóujú", "translation": "почтовое отделение" },
    { "lesson": 13, "hieroglyph": "邮票", "pinyin": "yóupiào", "translation": "почтовая марка" },
    { "lesson": 13, "hieroglyph": "教授", "pinyin": "jiàoshòu", "translation": "профессор" },
    { "lesson": 13, "hieroglyph": "名片", "pinyin": "míngpiàn", "translation": "визитка" },
    { "lesson": 13, "hieroglyph": "绍", "pinyin": "shào", "translation": "наследование" },
    { "lesson": 13, "hieroglyph": "对", "pinyin": "duì", "translation": "правильный верный" },
    { "lesson": 13, "hieroglyph": "了", "pinyin": "le", "translation": "модальное вспомогательное слово" },
    { "lesson": 13, "hieroglyph": "和", "pinyin": "hé", "translation": "и, с" },
    { "lesson": 13, "hieroglyph": "说", "pinyin": "shuō", "translation": "говорить" },
    { "lesson": 13, "hieroglyph": "兑", "pinyin": "yuè", "translation": "радость" },
    { "lesson": 13, "hieroglyph": "名字", "pinyin": "míngzi", "translation": "имя (человека)" },
    { "lesson": 13, "hieroglyph": "字", "pinyin": "zì", "translation": "иероглиф" },
    { "lesson": 13, "hieroglyph": "喂", "pinyin": "wèi", "translation": "\"эй\"; \"алло\"" },
    { "lesson": 13, "hieroglyph": "啊", "pinyin": "à", "translation": "\"а\", \"ах\" (междомет)" },
    { "lesson": 13, "hieroglyph": "商", "pinyin": "shāng", "translation": "торговля" },
    { "lesson": 13, "hieroglyph": "店", "pinyin": "diàn", "translation": "лавочка магазин" },
    { "lesson": 13, "hieroglyph": "商店", "pinyin": "shāngdiàn", "translation": "магазин" },
    { "lesson": 13, "hieroglyph": "买", "pinyin": "măi", "translation": "покупать" },
    { "lesson": 13, "hieroglyph": "卖", "pinyin": "mài", "translation": "продавать" },
    { "lesson": 13, "hieroglyph": "买卖", "pinyin": "măimài", "translation": "торги" },
    { "lesson": 13, "hieroglyph": "笔", "pinyin": "bĭ", "translation": "ручка карандаш кисть" },
    { "lesson": 13, "hieroglyph": "犹太人", "pinyin": "yoútáirēn", "translation": "еврей :)" },
    { "lesson": 13, "hieroglyph": "纸", "pinyin": "zhĭ", "translation": "бумага" },
    { "lesson": 13, "hieroglyph": "来", "pinyin": "lái", "translation": "приезжать приходить" },
    { "lesson": 13, "hieroglyph": "介绍", "pinyin": "jièshào", "translation": "представлять (кого-то)" },
    { "lesson": 13, "hieroglyph": "介", "pinyin": "jiè", "translation": "посредник" },
    { "lesson": 13, "hieroglyph": "广", "pinyin": "", "translation": "навес" },
    { "lesson": 13, "hieroglyph": "力", "pinyin": "lì", "translation": "сила" },
    { "lesson": 13, "hieroglyph": "亇", "pinyin": "zhú", "translation": "бамбук" },
    { "lesson": 13, "hieroglyph": "毛", "pinyin": "máo", "translation": "шерсть, волосы, оперение" },
    { "lesson": 13, "hieroglyph": "禾", "pinyin": "hé", "translation": "злак" },
    { "lesson": 13, "hieroglyph": "攵", "pinyin": "", "translation": "бить" },
    { "lesson": 13, "hieroglyph": "爫(кр), 爪(полн)", "pinyin": "zhăo", "translation": "когти" },
    { "lesson": 13, "hieroglyph": "片", "pinyin": "piàn", "translation": "карточка, пластинка, щепка" },
    { "lesson": 14, "hieroglyph": "北京", "pinyin": "Běijīng", "translation": "Пекин" },
    { "lesson": 14, "hieroglyph": "职员", "pinyin": "zhíyuán", "translation": "служащий, сотрудник" },
    { "lesson": 14, "hieroglyph": "职", "pinyin": "zhí", "translation": "должность, служебные обязанности" },
    { "lesson": 14, "hieroglyph": "员", "pinyin": "yuán", "translation": "работник, сотрудник, член :)" },
    { "lesson": 14, "hieroglyph": "工程师", "pinyin": "gōngchéngshī", "translation": "инженер" },
    { "lesson": 14, "hieroglyph": "经理", "pinyin": "jīnglǐ", "translation": "директор, управляющий" },
    { "lesson": 14, "hieroglyph": "公司", "pinyin": "gōngsī", "translation": "компания, фирма" },
    { "lesson": 14, "hieroglyph": "国外", "pinyin": "guó wài", "translation": "\"за рубежом\"" },
    { "lesson": 14, "hieroglyph": "登记表", "pinyin": "dēngjì bǎo", "translation": "регистрационная карточка" },
    { "lesson": 14, "hieroglyph": "做", "pinyin": "zuò", "translation": "делать" },
    { "lesson": 14, "hieroglyph": "工作", "pinyin": "gōngzuò", "translation": "работать, работа" },
    { "lesson": 14, "hieroglyph": "想", "pinyin": "xiăng", "translation": "думать, скучать" },
    { "lesson": 14, "hieroglyph": "家", "pinyin": "jiā", "translation": "дом, семья" },
    { "lesson": 14, "hieroglyph": "有", "pinyin": "yŏu", "translation": "иметь, обладать" },
    { "lesson": 14, "hieroglyph": "没", "pinyin": "méi", "translation": "нет" },
    { "lesson": 14, "hieroglyph": "妹妹", "pinyin": "mèimei", "translation": "младшая сестра" },
    { "lesson": 14, "hieroglyph": "姐姐", "pinyin": "jiĕjie", "translation": "старшая сестра" },
    { "lesson": 14, "hieroglyph": "银行", "pinyin": "yínháng", "translation": "банк" },
    { "lesson": 14, "hieroglyph": "爱人", "pinyin": "àirén", "translation": "муж/жена" },
    { "lesson": 14, "hieroglyph": "书店", "pinyin": "shūdiàn", "translation": "книжный магазин" },
    { "lesson": 14, "hieroglyph": "孩子", "pinyin": "háizi", "translation": "ребёнок, дитя" },
    { "lesson": 14, "hieroglyph": "给", "pinyin": "gĕi", "translation": "давать, предлог дательного падежа" },
    { "lesson": 14, "hieroglyph": "写", "pinyin": "xiĕ", "translation": "писать" },
    { "lesson": 14, "hieroglyph": "信", "pinyin": "xìn", "translation": "письмо" },
    { "lesson": 14, "hieroglyph": "告诉", "pinyin": "gàosu", "translation": "сказать, сообщить" },
    { "lesson": 14, "hieroglyph": "银", "pinyin": "yín", "translation": "серебро" },
    { "lesson": 14, "hieroglyph": "行", "pinyin": "háng", "translation": "контора, магазин, ряд, профессия" },
    { "lesson": 14, "hieroglyph": "爱", "pinyin": "ài", "translation": "любить" },
    { "lesson": 14, "hieroglyph": "工", "pinyin": "gōng", "translation": "работа" },
    { "lesson": 14, "hieroglyph": "豕", "pinyin": "shǐ", "translation": "свинья" },
    { "lesson": 14, "hieroglyph": "金", "pinyin": "jīn", "translation": "золото, металл" },
    { "lesson": 14, "hieroglyph": "耳", "pinyin": "ěr", "translation": "ухо" },
    { "lesson": 14, "hieroglyph": "豆", "pinyin": "dòu", "translation": "боб (растение)" },
    { "lesson": 14, "hieroglyph": "厶", "pinyin": "sī", "translation": "частный, личный" },
    { "lesson": 15, "hieroglyph": "班", "pinyin": "bān", "translation": "группа, класс" },
    { "lesson": 15, "hieroglyph": "教室", "pinyin": "jiàoshì", "translation": "аудитория, класс" },
    { "lesson": 15, "hieroglyph": "实验室", "pinyin": "shíyànshì", "translation": "лаборатория" },
    { "lesson": 15, "hieroglyph": "借", "pinyin": "jiè", "translation": "брать/давать взаймы" },
    { "lesson": 15, "hieroglyph": "生词", "pinyin": "shēngcí", "translation": "новое слово" },
    { "lesson": 15, "hieroglyph": "医院", "pinyin": "yīyuàn", "translation": "больница" },
    { "lesson": 15, "hieroglyph": "医", "pinyin": "yī", "translation": "медицина" },
    { "lesson": 15, "hieroglyph": "院", "pinyin": "yuàn", "translation": "двор, учреждение" },
    { "lesson": 15, "hieroglyph": "口", "pinyin": "kǒu", "translation": "сч. слово(численность семьи)" },
    { "lesson": 15, "hieroglyph": "帮助", "pinyin": "bāngzhù", "translation": "помогать" },
    { "lesson": 15, "hieroglyph": "学生城", "pinyin": "xuéshēng_chéng", "translation": "студгородок" },
    { "lesson": 15, "hieroglyph": "加", "pinyin": "jiā", "translation": "операция сложения" },
    { "lesson": 15, "hieroglyph": "减", "pinyin": "jiǎn", "translation": "операция вычитания" },
    { "lesson": 15, "hieroglyph": "得", "pinyin": "dé", "translation": "получать (результат арефметич. действия)" },
    { "lesson": 15, "hieroglyph": "丈夫", "pinyin": "zhàngfū", "translation": "муж" },
    { "lesson": 15, "hieroglyph": "中文", "pinyin": "zhōngwén", "translation": "китайский язык" },
    { "lesson": 15, "hieroglyph": "系", "pinyin": "Xì", "translation": "факультет" },
    { "lesson": 15, "hieroglyph": "个", "pinyin": "gè", "translation": "счетное слово" },
    { "lesson": 15, "hieroglyph": "几", "pinyin": "jǐ", "translation": "сколько, несколько (не больше десяти)" },
    { "lesson": 15, "hieroglyph": "教", "pinyin": "jiào", "translation": "учить, обучать" },
    { "lesson": 15, "hieroglyph": "语法", "pinyin": "yǔfǎ", "translation": "грамматика" },
    { "lesson": 15, "hieroglyph": "法", "pinyin": "fǎ", "translation": "закон, право, метод, способ" },
    { "lesson": 15, "hieroglyph": "汉字", "pinyin": "hànzì", "translation": "китайский иероглиф" },
    { "lesson": 15, "hieroglyph": "还", "pinyin": "hái", "translation": "еще, все еще, все же" },
    { "lesson": 15, "hieroglyph": "口语", "pinyin": "kǒuyǔ", "translation": "устная речь" },
    { "lesson": 15, "hieroglyph": "不敢当", "pinyin": "bù gǎn dāng", "translation": "что вы! не считаю себя таковым!" },
    { "lesson": 15, "hieroglyph": "互相", "pinyin": "hùxiāng", "translation": "взаимно, обоюдно, друг друга" },
    { "lesson": 15, "hieroglyph": "新", "pinyin": "xīn", "translation": "новый, свежий" },
    { "lesson": 15, "hieroglyph": "阅览室", "pinyin": "yuèlǎnshì", "translation": "читальный зал" },
    { "lesson": 15, "hieroglyph": "阅", "pinyin": "yuè", "translation": "просматривать" },
    { "lesson": 15, "hieroglyph": "览", "pinyin": "lǎn", "translation": "осматривать, знакомиться" },
    { "lesson": 15, "hieroglyph": "室", "pinyin": "shì", "translation": "комната, зал" },
    { "lesson": 15, "hieroglyph": "阅览", "pinyin": "yuèlǎn", "translation": "читать, просматривать" },
    { "lesson": 15, "hieroglyph": "杂志", "pinyin": "zázhì", "translation": "журнал" },
    { "lesson": 15, "hieroglyph": "报纸", "pinyin": "bàozhǐ", "translation": "газета" },
    { "lesson": 15, "hieroglyph": "本", "pinyin": "běn", "translation": "сч. слово(книги, журналы)" },
    { "lesson": 15, "hieroglyph": "图书馆", "pinyin": "túshūguǎn", "translation": "библиотека" },
    { "lesson": 15, "hieroglyph": "图书", "pinyin": "túshū", "translation": "библио-, книжный" },
    { "lesson": 15, "hieroglyph": "馆", "pinyin": "guǎn", "translation": "павильон, заведение" },
    { "lesson": 15, "hieroglyph": "斤", "pinyin": "jīn", "translation": "топор" },
    { "lesson": 15, "hieroglyph": "士", "pinyin": "shì", "translation": "воин" },
    { "lesson": 15, "hieroglyph": "食", "pinyin": "shí", "translation": "еда" },
    { "lesson": 16, "hieroglyph": "蓝", "pinyin": "lán", "translation": "синий, голубой" },
    { "lesson": 16, "hieroglyph": "上衣", "pinyin": "shàngyī", "translation": "верхняя одежда, куртка, пиджак" },
    { "lesson": 16, "hieroglyph": "上", "pinyin": "shàng", "translation": "верхний" },
    { "lesson": 16, "hieroglyph": "衣", "pinyin": "yī", "translation": "одежда" },
    { "lesson": 16, "hieroglyph": "裤子", "pinyin": "kùzi", "translation": "брюки" },
    { "lesson": 16, "hieroglyph": "大衣", "pinyin": "dàyī", "translation": "пальто" },
    { "lesson": 16, "hieroglyph": "黑", "pinyin": "hēi", "translation": "чернрый" },
    { "lesson": 16, "hieroglyph": "剧场", "pinyin": "jùchǎng", "translation": "театр, зрительный зал" },
    { "lesson": 16, "hieroglyph": "场", "pinyin": "chǎng", "translation": "площадка, спортивное поле, сцена, сч. слово (сеанс)" },
    { "lesson": 16, "hieroglyph": "座位", "pinyin": "zuòwèi", "translation": "сиденье, место" },
    { "lesson": 16, "hieroglyph": "青蛙", "pinyin": "qīngwā", "translation": "лягушка" },
    { "lesson": 16, "hieroglyph": "嘴", "pinyin": "zuǐ", "translation": "рот" },
    { "lesson": 16, "hieroglyph": "眼睛", "pinyin": "yǎnjīng", "translation": "глаза" },
    { "lesson": 16, "hieroglyph": "腿", "pinyin": "tuǐ", "translation": "нога" },
    { "lesson": 16, "hieroglyph": "动画片", "pinyin": "dònghuàpiān", "translation": "мультфильм" },
    { "lesson": 16, "hieroglyph": "妻子", "pinyin": "qīzǐ", "translation": "жена" },
    { "lesson": 16, "hieroglyph": "条", "pinyin": "tiáo", "translation": "сч. слово (длинные объекты)" },
    { "lesson": 16, "hieroglyph": "裙子", "pinyin": "qúnzi", "translation": "юбка" },
    { "lesson": 16, "hieroglyph": "两", "pinyin": "liǎng", "translation": "два" },
    { "lesson": 16, "hieroglyph": "张", "pinyin": "zhāng", "translation": "сч. слово (ровные, плоские предметы)" },
    { "lesson": 16, "hieroglyph": "票", "pinyin": "piào", "translation": "билет" },
    { "lesson": 16, "hieroglyph": "京剧", "pinyin": "jīngjù", "translation": "пекинская опера" },
    { "lesson": 16, "hieroglyph": "剧", "pinyin": "jù", "translation": "спектакль, пьеса" },
    { "lesson": 16, "hieroglyph": "晚上", "pinyin": "wǎnshàng", "translation": "вечер, вечером" },
    { "lesson": 16, "hieroglyph": "太", "pinyin": "tài", "translation": "слишком, чрезмерно" },
    { "lesson": 16, "hieroglyph": "从", "pinyin": "cóng", "translation": "из, от, с" },
    { "lesson": 16, "hieroglyph": "找", "pinyin": "zhǎo", "translation": "искать" },
    { "lesson": 16, "hieroglyph": "旧", "pinyin": "jiù", "translation": "старый, подержанный, БУ" },
    { "lesson": 16, "hieroglyph": "穿", "pinyin": "chuān", "translation": "надевать, одевать, носить" },
    { "lesson": 16, "hieroglyph": "件", "pinyin": "jiàn", "translation": "сч. слово (для предметов одежды)" },
    { "lesson": 16, "hieroglyph": "衬衫", "pinyin": "chènshān", "translation": "мужская рубашка, женская блузка" },
    { "lesson": 16, "hieroglyph": "绿", "pinyin": "lù", "translation": "зеленый" },
    { "lesson": 17, "hieroglyph": "上班", "pinyin": "shàngbān", "translation": "идти на работу, быть на работе" },
    { "lesson": 17, "hieroglyph": "班", "pinyin": "bān", "translation": "рабочая смена" },
    { "lesson": 17, "hieroglyph": "下班", "pinyin": "xiàbān", "translation": "заканчивать работу" },
    { "lesson": 17, "hieroglyph": "电影院", "pinyin": "diànyǐngyuàn", "translation": "кинотеатр" },
    { "lesson": 17, "hieroglyph": "表", "pinyin": "biǎo", "translation": "наручные/карманные часы" },
    { "lesson": 17, "hieroglyph": "钟", "pinyin": "zhōng", "translation": "настенные/настольные/башенные часы" },
    { "lesson": 17, "hieroglyph": "以前", "pinyin": "yǐqián", "translation": "раньше, прежде, до" },
    { "lesson": 17, "hieroglyph": "前", "pinyin": "qián", "translation": "впереди, передний; предшествующий; раньше" },
    { "lesson": 17, "hieroglyph": "课本", "pinyin": "kèběn", "translation": "учебник" },
    { "lesson": 17, "hieroglyph": "课文", "pinyin": "kèwén", "translation": "учебный текст" },
    { "lesson": 17, "hieroglyph": "吧", "pinyin": "ba", "translation": "предложение что-то сделать; вежливое предположение/вопрос" },
    { "lesson": 17, "hieroglyph": "明天", "pinyin": "míngtiān", "translation": "завтра" },
    { "lesson": 17, "hieroglyph": "今天", "pinyin": "jīntiān", "translation": "сегодня" },
    { "lesson": 17, "hieroglyph": "下午", "pinyin": "xiàwǔ", "translation": "во второй половине дня" },
    { "lesson": 17, "hieroglyph": "快", "pinyin": "kuài", "translation": "спешить" },
    { "lesson": 17, "hieroglyph": "便条", "pinyin": "biàntiáo", "translation": "записка" },
    { "lesson": 17, "hieroglyph": "门口", "pinyin": "ménkǒu", "translation": "двери, вход" },
    { "lesson": 17, "hieroglyph": "回家", "pinyin": "huíjiā", "translation": "идти домой" },
    { "lesson": 17, "hieroglyph": "书法", "pinyin": "shūfǎ", "translation": "каллиграфия" },
    { "lesson": 17, "hieroglyph": "点", "pinyin": "diǎn", "translation": "сч. слово (час)" },
    { "lesson": 17, "hieroglyph": "食堂", "pinyin": "shítáng", "translation": "столовая" },
    { "lesson": 17, "hieroglyph": "食", "pinyin": "shí", "translation": "еда" },
    { "lesson": 17, "hieroglyph": "堂", "pinyin": "táng", "translation": "зал" },
    { "lesson": 17, "hieroglyph": "差", "pinyin": "chà", "translation": "недоставать" },
    { "lesson": 17, "hieroglyph": "分", "pinyin": "fēn", "translation": "сч. слово (минута)" },
    { "lesson": 17, "hieroglyph": "刻", "pinyin": "kè", "translation": "сч. слово (четверть)" },
    { "lesson": 17, "hieroglyph": "上", "pinyin": "shàng", "translation": "ходить, посещать, проводить (про занятия, школу)" },
    { "lesson": 17, "hieroglyph": "课", "pinyin": "kè", "translation": "урок, занятия" },
    { "lesson": 17, "hieroglyph": "下", "pinyin": "xià", "translation": "заканчивать" },
    { "lesson": 17, "hieroglyph": "以后", "pinyin": "yǐhòu", "translation": "после, позже, после того, как" },
    { "lesson": 17, "hieroglyph": "后", "pinyin": "hòu", "translation": "сзади, задний; потом, будущий" },
    { "lesson": 17, "hieroglyph": "事儿", "pinyin": "shìr", "translation": "дело, событие, работа" },
    { "lesson": 17, "hieroglyph": "回", "pinyin": "huí", "translation": "возвращаться, поворачивать обратно" },
    { "lesson": 17, "hieroglyph": "跟", "pinyin": "gēn", "translation": "(вместе) с; идти с, следовать за" },
    { "lesson": 17, "hieroglyph": "一起", "pinyin": "yìqǐ", "translation": "вместе, совместно" },
    { "lesson": 17, "hieroglyph": "电影", "pinyin": "diànyǐng", "translation": "фильм, кино" },
    { "lesson": 17, "hieroglyph": "电", "pinyin": "diàn", "translation": "электричество, электронный" },
    { "lesson": 17, "hieroglyph": "咖啡馆", "pinyin": "kāfēiguǎn", "translation": "кафе" },
    { "lesson": 17, "hieroglyph": "咖啡", "pinyin": "kāfēi", "translation": "кофе" },
    { "lesson": 17, "hieroglyph": "半", "pinyin": "bàn", "translation": "половина" },
    { "lesson": 17, "hieroglyph": "啊", "pinyin": "a", "translation": "модальная частица" },
    { "lesson": 17, "hieroglyph": "等", "pinyin": "děng", "translation": "ждать, ожидать" },
    { "lesson": 17, "hieroglyph": "走", "pinyin": "zǒu", "translation": "идти пешком" },
    { "lesson": 17, "hieroglyph": "路", "pinyin": "lù", "translation": "дорога, путь, улица" },
    { "lesson": 17, "hieroglyph": "弓", "pinyin": "gōng", "translation": "лук" },
    { "lesson": 17, "hieroglyph": "长", "pinyin": "zhǎng; cháng", "translation": "старший, длинный" },
    { "lesson": 17, "hieroglyph": "穴", "pinyin": "xué", "translation": "пещера" },
    { "lesson": 17, "hieroglyph": "牙", "pinyin": "yá", "translation": "зуб" },
    { "lesson": 17, "hieroglyph": "牛", "pinyin": "niú", "translation": "корова" },
    { "lesson": 17, "hieroglyph": "彡", "pinyin": "shān", "translation": "перья" },
    { "lesson": 17, "hieroglyph": "虫", "pinyin": "chóng", "translation": "двигаться; движение" },
    { "lesson": 17, "hieroglyph": "角", "pinyin": "jiǎo", "translation": "угол; рог" },
    { "lesson": 18, "hieroglyph": "中午", "pinyin": "zhōngwǔ", "translation": "полдень" },
    { "lesson": 18, "hieroglyph": "历史", "pinyin": "lìshǐ", "translation": "история" },
    { "lesson": 18, "hieroglyph": "文学", "pinyin": "wénxué", "translation": "литература" },
    { "lesson": 18, "hieroglyph": "天", "pinyin": "tiān", "translation": "день" },
    { "lesson": 18, "hieroglyph": "每", "pinyin": "měi", "translation": "каждый, всякий" },
    { "lesson": 18, "hieroglyph": "起床", "pinyin": "qǐchuáng", "translation": "вставать (с постели)" },
    { "lesson": 18, "hieroglyph": "起", "pinyin": "qǐ", "translation": "вставать; подниматься" },
    { "lesson": 18, "hieroglyph": "床", "pinyin": "chuáng", "translation": "кровать" },
    { "lesson": 18, "hieroglyph": "上午", "pinyin": "shàngwǔ", "translation": "первая половина дня" },
    { "lesson": 18, "hieroglyph": "午", "pinyin": "wǔ", "translation": "полдень" },
    { "lesson": 18, "hieroglyph": "吃", "pinyin": "chī", "translation": "есть, кушать" },
    { "lesson": 18, "hieroglyph": "饭", "pinyin": "fàn", "translation": "вареный рис; еда, пища" },
    { "lesson": 18, "hieroglyph": "下午", "pinyin": "xiàwǔ", "translation": "вторая половина дня" },
    { "lesson": 18, "hieroglyph": "休息", "pinyin": "xiūxī", "translation": "отдыхать" },
    { "lesson": 18, "hieroglyph": "有时候", "pinyin": "yǒushíhòu", "translation": "иногда, порой" },
    { "lesson": 18, "hieroglyph": "时候", "pinyin": "shíhòu", "translation": "время, пора" },
    { "lesson": 18, "hieroglyph": "问题", "pinyin": "wèntí", "translation": "вопрос, проблема" },
    { "lesson": 18, "hieroglyph": "睡觉", "pinyin": "shuìjiào", "translation": "спать; ложиться спать" },
    { "lesson": 19, "hieroglyph": "要", "pinyin": "yào", "translation": "желать, хотеть, намереваться, нужно, должно" },
    { "lesson": 19, "hieroglyph": "服务员", "pinyin": "fúwùyuán", "translation": "официант" },
    { "lesson": 19, "hieroglyph": "杯", "pinyin": "bēi", "translation": "сч. слово (чашка, стакан, рюмка)" },
    { "lesson": 19, "hieroglyph": "姑娘", "pinyin": "gūniang", "translation": "девушка" },
    { "lesson": 19, "hieroglyph": "喜欢", "pinyin": "xǐhuan", "translation": "нравиться, любить" },
    { "lesson": 19, "hieroglyph": "花茶", "pinyin": "huāchá", "translation": "ароматизированный чай" },
    { "lesson": 19, "hieroglyph": "红茶", "pinyin": "hóngchá", "translation": "черный чай" },
    { "lesson": 19, "hieroglyph": "还是", "pinyin": "háishi", "translation": "или" },
    { "lesson": 19, "hieroglyph": "可乐", "pinyin": "kělè", "translation": "(кока)кола" },
    { "lesson": 19, "hieroglyph": "瓶", "pinyin": "píng", "translation": "сч. слово (бутылка)" },
    { "lesson": 19, "hieroglyph": "啤酒", "pinyin": "píjiǔ", "translation": "пиво" },
    { "lesson": 19, "hieroglyph": "听", "pinyin": "tīng", "translation": "слушать" },
    { "lesson": 19, "hieroglyph": "民歌", "pinyin": "míngē", "translation": "народная песня" },
    { "lesson": 19, "hieroglyph": "古典", "pinyin": "gǔdiǎn", "translation": "классика, классический" },
    { "lesson": 19, "hieroglyph": "音乐", "pinyin": "yīnyuè", "translation": "музыка" },
    { "lesson": 19, "hieroglyph": "现代", "pinyin": "xiàndài", "translation": "современность, современный" },
    { "lesson": 19, "hieroglyph": "唱", "pinyin": "chàng", "translation": "петь" },
    { "lesson": 19, "hieroglyph": "歌儿", "pinyin": "gēr", "translation": "песня" },
    { "lesson": 19, "hieroglyph": "让", "pinyin": "ràng", "translation": "просить, велеть, разрешать" },
    { "lesson": 19, "hieroglyph": "别", "pinyin": "bié", "translation": "не, не надо, нельзя" },
    { "lesson": 19, "hieroglyph": "枝", "pinyin": "zhī", "translation": "сч. слово (ветка)" },
    { "lesson": 19, "hieroglyph": "苹果", "pinyin": "píngguǒ", "translation": "яблоко" },
    { "lesson": 19, "hieroglyph": "果子", "pinyin": "guǒzi", "translation": "плод, фрукт" },
    { "lesson": 19, "hieroglyph": "香蕉", "pinyin": "xiāngjiāo", "translation": "банан" },
    { "lesson": 19, "hieroglyph": "葡萄", "pinyin": "pútao", "translation": "виноград" },
    { "lesson": 19, "hieroglyph": "橙子", "pinyin": "chéngzi", "translation": "апельсин" },
    { "lesson": 19, "hieroglyph": "橘子", "pinyin": "júzi", "translation": "мандарин" },
    { "lesson": 19, "hieroglyph": "水果", "pinyin": "shuǐguǒ", "translation": "фрукты" },
    { "lesson": 19, "hieroglyph": "唱片", "pinyin": "chàngpiàn", "translation": "пластинка" },
    { "lesson": 19, "hieroglyph": "糖", "pinyin": "táng", "translation": "сахар, конфета" },
    { "lesson": 19, "hieroglyph": "糖果", "pinyin": "tángguǒ", "translation": "конфеты, сладости" },
    { "lesson": 19, "hieroglyph": "绿茶", "pinyin": "lǜchá", "translation": "зеленый чай" },
    { "lesson": 19, "hieroglyph": "果汁", "pinyin": "guǒzhī", "translation": "фруктовый сок" },
    { "lesson": 19, "hieroglyph": "公斤", "pinyin": "gōngjīn", "translation": "килограмм" },
    { "lesson": 19, "hieroglyph": "加", "pinyin": "jiā", "translation": "добавлять" },
    { "lesson": 19, "hieroglyph": "茉莉花", "pinyin": "mòlìhuā", "translation": "жасмин" },
    { "lesson": 19, "hieroglyph": "可口可乐", "pinyin": "kěkǒukělè", "translation": "кока-кола" },
    { "lesson": 19, "hieroglyph": "光盘", "pinyin": "guāngpán", "translation": "компакт-диск" },
    { "lesson": 19, "hieroglyph": "课本", "pinyin": "kèběn", "translation": "учебник" },
    { "lesson": 19, "hieroglyph": "留念", "pinyin": "liúniàn", "translation": "оставлять на память" },
    { "lesson": 19, "hieroglyph": "自行车", "pinyin": "zìxíngzhē", "translation": "велосипед" },
    { "lesson": 19, "hieroglyph": "复习", "pinyin": "fùxí", "translation": "повторять изученное" },
    { "lesson": 19, "hieroglyph": "查", "pinyin": "chá", "translation": "просматривать, проверять" },
    { "lesson": 19, "hieroglyph": "人家", "pinyin": "rénjiā", "translation": "люди, окружающие" },
    { "lesson": 19, "hieroglyph": "新出的", "pinyin": "xīnchūde", "translation": "новый, недавно вышедший" },
    { "lesson": 19, "hieroglyph": "男孩儿", "pinyin": "nánháir", "translation": "мальчик" },
    { "lesson": 19, "hieroglyph": "女孩儿", "pinyin": "nǚháir", "translation": "девочка" },
    { "lesson": 20, "hieroglyph": "月", "pinyin": "yuè", "translation": "месяц" },
    { "lesson": 20, "hieroglyph": "日", "pinyin": "rì", "translation": "день, число, дата" },
    { "lesson": 20, "hieroglyph": "生日", "pinyin": "shēngrì", "translation": "день рождения" },
    { "lesson": 20, "hieroglyph": "今天", "pinyin": "jīntiān", "translation": "сегодня" },
    { "lesson": 20, "hieroglyph": "班", "pinyin": "bān", "translation": "группа, класс" },
    { "lesson": 20, "hieroglyph": "辅导", "pinyin": "fǔdǎo", "translation": "давать консультацию" },
    { "lesson": 20, "hieroglyph": "号", "pinyin": "hào", "translation": "число, дата" },
    { "lesson": 20, "hieroglyph": "空儿", "pinyin": "kòngr", "translation": "свободное время" },
    { "lesson": 20, "hieroglyph": "今年", "pinyin": "jīnnián", "translation": "этот год" },
    { "lesson": 20, "hieroglyph": "岁", "pinyin": "suì", "translation": "возраст" },
    { "lesson": 20, "hieroglyph": "祝贺", "pinyin": "zhùhè", "translation": "поздравлять" },
    { "lesson": 20, "hieroglyph": "舞会", "pinyin": "wǔhuì", "translation": "танцы" },
    { "lesson": 20, "hieroglyph": "会", "pinyin": "huì", "translation": "собрание, совещание" },
    { "lesson": 20, "hieroglyph": "参加", "pinyin": "cānjiā", "translation": "участвовать, присутствовать" },
    { "lesson": 20, "hieroglyph": "同学", "pinyin": "tóngxué", "translation": "одноклассник" },
    { "lesson": 20, "hieroglyph": "一定", "pinyin": "yídìng", "translation": "определенный, установленный; обязательно" },
    { "lesson": 20, "hieroglyph": "有意思", "pinyin": "yǒuyìsī", "translation": "интересный, интересно" },
    { "lesson": 20, "hieroglyph": "星期", "pinyin": "xīngqī", "translation": "неделя" },
    { "lesson": 20, "hieroglyph": "星", "pinyin": "xīng", "translation": "звезда" },
    { "lesson": 20, "hieroglyph": "期", "pinyin": "qī", "translation": "период" },
    { "lesson": 20, "hieroglyph": "星期日", "pinyin": "xīngqīrì", "translation": "воскресенье" },
    { "lesson": 20, "hieroglyph": "知道", "pinyin": "zhīdào", "translation": "знать" },
    { "lesson": 20, "hieroglyph": "地址", "pinyin": "dìzhǐ", "translation": "адрес" },
    { "lesson": 20, "hieroglyph": "年", "pinyin": "nián", "translation": "год" },
    { "lesson": 20, "hieroglyph": "去年", "pinyin": "qùnián", "translation": "прошлый год" },
    { "lesson": 20, "hieroglyph": "明年", "pinyin": "míngnián", "translation": "будущий год" },
    { "lesson": 20, "hieroglyph": "音乐会", "pinyin": "yīnyuèhuì", "translation": "концерт" },
    { "lesson": 20, "hieroglyph": "结婚", "pinyin": "jiéhūn", "translation": "жениться, вступать в брак" },
    { "lesson": 20, "hieroglyph": "对不起", "pinyin": "duìbùqǐ", "translation": "извините, виноват" },
    { "lesson": 20, "hieroglyph": "约会", "pinyin": "yuēhuì", "translation": "свидание" },
    { "lesson": 20, "hieroglyph": "没关系", "pinyin": "méiguānxì", "translation": "(вежл.) ничего страшного" },
    { "lesson": 20, "hieroglyph": "谈", "pinyin": "tán", "translation": "разгоаривать, беседовать, обуждать" },
    { "lesson": 20, "hieroglyph": "昨天", "pinyin": "zuótiān", "translation": "вчера" },
    { "lesson": 20, "hieroglyph": "前天", "pinyin": "qiántiān", "translation": "позавчера" },
    { "lesson": 20, "hieroglyph": "后天", "pinyin": "hòutiān", "translation": "послезавтра" },
    { "lesson": 20, "hieroglyph": "次", "pinyin": "cì", "translation": "(сч. сл.) раз" },
    { "lesson": 20, "hieroglyph": "听写", "pinyin": "tīngxiě", "translation": "диктант" },
    { "lesson": 20, "hieroglyph": "俱乐部", "pinyin": "jùlèbù", "translation": "клуб" },
    { "lesson": 20, "hieroglyph": "举行", "pinyin": "jǔxíng", "translation": "проводить, устраивать" },
    { "lesson": 20, "hieroglyph": "亲爱", "pinyin": "qīnài", "translation": "дорогой (обращение)" },
    { "lesson": 20, "hieroglyph": "祝", "pinyin": "zhù", "translation": "желать" },
    { "lesson": 20, "hieroglyph": "健康", "pinyin": "jiànkāng", "translation": "здоровье, здоровый" },
    { "lesson": 20, "hieroglyph": "通知", "pinyin": "tōngzhī", "translation": "объявление, сообщение, извещение" },
]